### PR TITLE
Fix spelling mistake and make task

### PR DESCRIPTION
**Pull request by JonahBraun**
This small PR fixes a few things and checks if the CLA bot is happy with me now.

### CODE REVIEW

**Comment by emailbob** [comment]
test this please

**Comment by chrislovecnm** [comment]
Bob any idea?

**Comment by emailbob** [comment]
test this please

**Comment by emailbob** [comment]
Not yet. Unfortunately I need to kick off a bunch of test builds to test any changes I make.

**Comment by emailbob** [comment]
Fixed

**Pull request merged**
