### PR TITLE
Added comments to the new section of the validate script

### PR DESCRIPTION
**Pull request by donovanjamesl**
Added the requested comments to the validate script.

### CODE REVIEW

**Comment by donovanjamesl** [comment]
test this please

**Comment by chrislovecnm** [comment]
```
* google_container_cluster.primary: googleapi: Error 409: Already exists: projects/pso-helmsman-cicd-infra/zones/us-west1-c/clusters/stackdriver-logging., alreadyExists
```

We may have a name collision

**Comment by chrislovecnm** [comment]
test this please

**Pull request merged**
