### PR TITLE
Update readme use make tasks.

### PR DESCRIPTION
**Pull request by JonahBraun**
This is a general cleanup of the readme and includes:

- Updated instructs to use make tasks instead of terraform/scripts.
- Quickstart and optimized demo usage instructions.

### CODE REVIEW

**Comment by emailbob** [comment]
test this please

**Comment by krzyzacy** [comment]
@chrislovecnm 
```
error:  "status code 403 not one of [201], body: {"message":"Must have admin rights to Repository.","documentation_url":"https://developer.github.com/v3/issues/assignees/#add-assignees-to-an-issue"}"   
```

**Comment by chrislovecnm** [comment]
@krzyzacy which user?

**Comment by JonahBraun** [comment]
I tried to do some history rewriting to resolve the CLA error as described in the help page it links to. The result is pretty ugly, so I'm going to abandon this PR and open a new one.

**Pull request closed without merging**
